env:
  DOCKER_COMPOSE_VERSION: 1.11.0

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose pull
  - docker-compose start

language: php

php:
  - 7.1
  - 7.0

before_script:
  - composer selfupdate
  - composer update

script:
  - vendor/bin/atoum
  - phantomjs Resources/js/run_jsunit.js Resources/js/manager_test.html
